#!/bin/bash

set -eu -o pipefail

DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/calcurse"

# Do not do anything when synchronizing with a CalDAV server.
test -f "$DATA_DIR/caldav/lock" && exit

# Run the CalDAV synchronization script in the background.
if test -d "$DATA_DIR/caldav" && command -v calcurse-caldav > /dev/null; then
	(cd "$DATA_DIR"; systemd-cat --identifier=calcurse-caldav calcurse-caldav) > /dev/null 2>&1 &
fi
