#!/bin/bash

set -u

SWAY_WALLPAPER_PATH="$HOME/.config/sway/default-bg"

function swaymsg-has-error() {
    local msg="$1"
    if [[ "$(jq '.[].success' <<< "$msg")" != "true" ]]; then
        return 0
    fi
    return 1
}

function swaymsg-get-error() {
    local msg="$1"
    if swaymsg-has-error "$msg"; then
        jq --raw-output '.[].error' <<< "$msg"
    fi
}

function main() {
    local mode="fill"
    local output="*"
    local copy=false
    local rest=()

    while [[ $# -gt 0 ]]; do
        case "$1" in
        -m|--mode)   mode="$2";    shift 2 ;;
        -o|--output) output="$2";  shift 2 ;;
        -c|--copy)   copy=true;    shift ;;
        -*|--*)      echo "Error: unknown option $1"; exit 1 ;;
        *)           rest+=("$1"); shift ;;
        esac
    done

    if test "${#rest[@]}" -ne 1 || test ! -f "${rest[0]}"; then
        echo "Error: no file found when setting wallpaper" > /dev/stderr
        exit 1
    fi

    local image="$(realpath ${rest[0]})"
    local result="$(swaymsg --raw output $output bg "$image" $mode)"

    if swaymsg-has-error "$result"; then
        echo "Error: $(swaymsg-get-error "$result")" > /dev/stderr
        exit 1
    fi

    if $copy; then
        cp --remove-destination "$image" "$SWAY_WALLPAPER_PATH"
    else
        ln --symbolic --force "$image" "$SWAY_WALLPAPER_PATH"
    fi
}

main "$@"
