# Configuration file for msmtp.
#
# This file is a template for Gmail servers, and can be used with msmtp with the following example
# command:
#
# msmtp -C <(USERNAME=<user> PASSWORD=<pass> HOSTNAME=<host> envsubst < <conf>)
#
# Where <user> is something like "user@test.com".

defaults
auth           on
tls            on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        ${MAIL_DATADIR}/msmtp.log

account  ${USERNAME}
host     smtp.gmail.com
port     587
from     ${USERNAME}
user     ${USERNAME}
password ${PASSWORD}

account default: ${USERNAME}
