#!/bin/bash
#
# Clock applet for i3bar.

onclick() {
	case ${1} in
	1)
		${CLOCK_CLICK_CMD}
		;;
	esac
}

clock() {
	output "$(icon "${ICON_CLOCK}") $(date +"${CLOCK_FORMAT}")"
	sleep $((60 - 10#$(date +"%S")))
}
