#!/bin/bash
# CPU applet for i3bar.
# Requirements: coretemp (for temperature readings)

cpu() {
	local status=$(head -n 1 /proc/stat | cut -d' ' -f3-)

	local idle_prev=$(echo ${PREV_STATUS} | awk '{print $4 + $5}')
	local idle_now=$(echo ${status} | awk '{print $4 + $5}')

	local nonidle_prev=$(echo ${PREV_STATUS} | awk '{print $1 + $2 + $3 + $6 + $7 + $8}')
	local nonidle_now=$(echo ${status} | awk '{print $1 + $2 + $3 + $6 + $7 + $8}')

	local total_prev=$((${idle_prev} + ${nonidle_prev}))
	local total_now=$((${idle_now} + ${nonidle_now}))

	local idle_delta=$((${idle_now} - ${idle_prev}))
	local total_delta=$((${total_now} - ${total_prev}))

	if [ ${total_delta} -eq 0 ]
	then
		local usage=0
	else
		local usage=$((100 * (${total_delta} - ${idle_delta}) / ${total_delta}))
	fi

	local temp=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp2_input | cut -c-2)
	PREV_STATUS="${status}"

	output "$(icon "${ICON_CPU}") ${usage}% $(icon "${ICON_TEMP}") ${temp}°C"
	sleep ${CPU_UPDATE_INTERVAL}
}

# Previous CPU status, calculated on init and every subsequent frame.
PREV_STATUS="$(head -n 1 /proc/stat | cut -d' ' -f3-)"