#!/bin/bash
# Keyboard layout applet for i3.
# Requirements: dbus, kbdd

DBUS_SEND="dbus-send --dest=ru.gentoo.KbddService /ru/gentoo/KbddService"

onclick() {
	case ${1} in
	1)
		$(${DBUS_SEND} ru.gentoo.kbdd.next_layout)
		;;
	esac
}

waitforsignal() {
	local signal="type='signal', interface='ru.gentoo.kbdd', member='layoutNameChanged'"
	dbus-monitor --session --profile "${signal}" | grep -m 0 '^sig.*KbddService'
}

keyboard() {
	local layout_index=$(${DBUS_SEND} --print-reply=literal ru.gentoo.kbdd.getCurrentLayout | awk '{print $2}')

	case "${KEYBOARD_LAYOUT_TYPE}" in
	long)
		local layout_name=$(${method_send} ru.gentoo.kbdd.getLayoutName uint32:${layout_index} | xargs)
		;;
	short)
		local layout_name=$(setxkbmap -print -verbose 10 | awk -v FS=',| +' -v n="${layout_index}" '/layout:/ {print $(n + 2)}')
		;;
	esac

	output "${layout_name}"
	waitforsignal
}
