#!/bin/bash
# Memory usage applet for i3bar.
# Requirements: GNU awk (though other versions may also work)

USAGE_CALCULATE=$(cat <<-'EOM'
	/^MemTotal/	{memtotal = ($2)/(1024)}
	/^MemFree/	{memfree = ($2)/(1024)}
	/^Buffers/	{buffers = ($2)/(1024)}
	/^Cached/	{cached = ($2)/(1024)}
	END {
		usedmem = memtotal - memfree - buffers - cached;
		usedperc = (usedmem / memtotal) * 100;
		printf("%d", usedperc);
	}
	EOM
)

memory() {
	local memusage=$(awk "${USAGE_CALCULATE}" < /proc/meminfo)

	output "$(icon "${ICON_MEMORY}") ${memusage}%"
	sleep ${MEMORY_UPDATE_INTERVAL}
}