#!/bin/bash
# Network applet for i3bar, using NetworkManager or Connman.
# Requirements: dbus, networkmanager (nmcli) or connman (connmanctl, connman-gtk)

onclick() {
	case ${1} in
	1)
		${NETWORK_CLICK_CMD}
		;;
	esac
}

waitforsignal() {
	case "${NETWORK_BACKEND}" in
	networkmanager)
		local signal="type='signal', interface='org.freedesktop.NetworkManager.AccessPoint'"
		dbus-monitor --system --profile "${signal}" | grep -m 0 '^sig.*NetworkManager'
		;;
	connman)
		local signal="type='signal', interface='net.connman.Service'"
		dbus-monitor --system --profile "${signal}" | grep -m 0 '^sig.*/net/connman'
		;;
	esac
}

network() {
	local result=()

	case "${NETWORK_BACKEND}" in
	networkmanager)
		local wired=$(nmcli -t -f STATE,TYPE,CONNECTION dev | grep '^connected:ethernet' | cut -d':' -f3)
		local wifi=$(nmcli -t -f ACTIVE,SSID,SIGNAL dev wifi | grep '^yes' | cut -d':' -f2-)
		;;
	connman)
		local wired="$(connmanctl services | awk '/^\*A?[O|R].+ethernet_/ {print $NF}')"
		local __wifi_active="$(connmanctl services | awk '/^\*A?[O|R].+wifi_/ {print $NF}')"

		if [ "x${__wifi_active}" != "x" ]
		then
			local __ssid="$(awk -F' = ' '/Name =/ {print $2}' <(echo "$(connmanctl services ${__wifi_active})"))"
			local __signal="$(awk -F' = ' '/Strength =/ {print $2}' <(echo "$(connmanctl services ${__wifi_active})"))"

			local wifi="${__ssid}:${__signal}"
		fi
		;;
	esac

	# Wired/Ethernet connection.
	if [ "x${wired}" != "x" ]
	then
		result+=("$(icon "${ICON_WIRED}")")
	fi

	# Wireless connection.
	if [ "x${wifi}" != "x" ]
	then
		local ssid=$(echo "${wifi}" | cut -d':' -f1)
		local signal=$(echo "${wifi}" | cut -d':' -f2)

		if [ "${signal}" -ge 80 ]
		then
			local wireless_icon="${ICON_WIRELESS_100}"
		elif [ "${signal}" -ge 50 ]
		then
			local wireless_icon="${ICON_WIRELESS_50}"
		elif [ "${signal}" -ge 30 ]
		then
			local wireless_icon="${ICON_WIRELESS_25}"
		else
			local wireless_icon="${ICON_WIRELESS_0}"
		fi

		result+=("$(icon "${wireless_icon}") ${ssid}")
	fi

	output "${result[*]}"
	waitforsignal
}
