#!/bin/bash
# Player applet for i3bar, using playerctl (MPRIS) or mpc (MPD).

onclick() {
	case ${1} in
	1)
		${PLAYER_CMD}
		;;
	esac
}

waitforsignal() {
	case "${PLAYER_BACKEND}" in
	mpris)
		local signal="type='signal', path='/org/mpris/MediaPlayer2'"
		timeout 30s dbus-monitor --session --profile "${signal}" | grep -m 0 '^sig.*MediaPlayer2'
		;;
	mpd)
		timeout 30s mpc idle
		;;
	esac
}

player() {
	case "${PLAYER_BACKEND}" in
	mpris)
		local status="$(playerctl status)"
		local artist="$(playerctl metadata artist)"
		local track="$(playerctl metadata title)"
		;;
	mpd)
		local status="$(mpc | awk 'NR==2 {print substr($1, 2, length($1) - 2)}')"
		local artist="$(mpc -f "%artist%" | awk '{print; exit}')"
		local track="$(mpc -f "%title%" | awk '{print; exit}')"
		;;
	esac

	case "${status,,}" in
	playing)
		local status_icon="${ICON_MUSIC_PLAY}"
		;;
	paused)
		local status_icon="${ICON_MUSIC_PAUSE}"
		;;
	*)
		output ""
		waitforsignal
		return
	esac

	# Keep full title under 40 characters, adding an ellipsis if needed.
	artist="$(echo "${artist}" | awk '{if(length($0)>20) print substr($0,1,20) "…"; else print}')"
	track="$(echo "${track}" | awk '{if(length($0)>20) print substr($0,1,20) "…"; else print}')"

	output "$(icon "${status_icon}") ${artist} - ${track}"
	waitforsignal
}
