#!/bin/bash
# Volume applet for i3bar, using Pulseaudio.
# Requirements: pulseaudio

onclick() {
	case ${1} in
	1)
		gnome-control-center sound
		;;
	4)
		(exec "${VOLUME_SCRIPT}" up)
		touch "${TEMP_PATH}/volume"
		;;
	5)
		(exec "${VOLUME_SCRIPT}" down)
		touch "${TEMP_PATH}/volume"
		;;
	esac
}

volume() {
	local status=$(exec "${VOLUME_SCRIPT}" get)
	local volume=$(echo "${status}" | cut -d: -f1)
	local mute=$(echo "${status}" | cut -d: -f2)

	if [ "${mute}" == "yes" ]
	then
		local volume_icon="${ICON_VOLUME_0}"
	elif [ ${volume} -ge 70 ]
	then
		local volume_icon="${ICON_VOLUME_100}"
	elif [ ${volume} -ge 40 ]
	then
		local volume_icon="${ICON_VOLUME_50}"
	elif [ ${volume} -ge 10 ]
	then
		local volume_icon="${ICON_VOLUME_25}"
	else
		local volume_icon="${ICON_VOLUME_0}"
	fi

	output "$(icon "${volume_icon}") ${volume:--}%"
	read < "${TEMP_PATH}/volume"
}

# Create named pipe for update event.
mkfifo "${TEMP_PATH}/volume"
