#!/bin/bash
#
# Mu integration with mail-sync.

function fetch-pre-hook() {
	return 0
}

function fetch-post-hook() {
	local account="$1"
	mu index --muhome="${MAIL_DATADIR}/.mu" --maildir="${MAIL_DATADIR}/${account}"
}

function account-setup-pre-hook() {
	return 0
}

function account-setup-post-hook() {
	return 0
}
