# Command-line flags used for all instances of Chromium.
#
# Enable Wayland support.
--ozone-platform=wayland
--gtk-version=4
--force-device-scale-factor=1

# Enable GPU acceleration.
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
