# Configuration file for mbsync.
#
# This file is a template for generic IMAP servers, and can be used with mbsync with the following
# example command:
#
# mbsync <user> -c <(USERNAME=<user> PASSWORD=<pass> HOSTNAME=<host> envsubst < <conf>)
#
# Where <user> is something like "user@test.com" and host is something like "mail.test.com".

IMAPAccount ${USERNAME}
Host ${HOSTNAME}
User ${USERNAME}
Pass ${PASSWORD}
SSLType IMAPS
CertificateFile /etc/ssl/certs/ca-certificates.crt

IMAPStore imap-remote
Account ${USERNAME}

MaildirStore imap-local
SubFolders Verbatim
Path ${MAIL_DATADIR}/${USERNAME}/
Inbox ${MAIL_DATADIR}/${USERNAME}/Inbox

Channel imap-default
Far :imap-remote:
Near :imap-local:
Patterns * INBOX
Create Both
Sync Pull Push New ReNew Flags
SyncState *

Group ${USERNAME}
Channel imap-default
