[terminal.shell]
args    = ["--login"]
program = "/usr/bin/fish"

[env]
TERM = "alacritty-direct"

[window]
decorations = "none"
decorations_theme_variant = "Dark"

[window.padding]
x = 20
y = 20

[font]
size = 19

[font.normal]
family = "Iosevka Nerd Mono"

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#2d2d2d"
foreground = "#d8d8d8"

[colors.cursor]
text   = "#181818"
cursor = "#d8d8d8"

[colors.normal]
black   = "#181818"
red     = "#ab4642"
green   = "#a1b56c"
yellow  = "#f7ca88"
blue    = "#7cafc2"
magenta = "#ba8baf"
cyan    = "#86c1b9"
white   = "#d8d8d8"

[colors.bright]
black   = "#585858"
red     = "#ab4642"
green   = "#a1b56c"
yellow  = "#f7ca88"
blue    = "#7cafc2"
magenta = "#ba8baf"
cyan    = "#86c1b9"
white   = "#f8f8f8"

[[hints.enabled]]
command         = "xdg-open"
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
binding         = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|news:|file:|ssh:|[a-z]+://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
