[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x585858"
blue = "0xb8b8b8"
cyan = "0xa16946"
green = "0x282828"
magenta = "0xe8e8e8"
red = "0xdc9656"
white = "0xf8f8f8"
yellow = "0x383838"

[colors.cursor]
cursor = "0xd8d8d8"
text = "0x181818"

[colors.normal]
black = "0x181818"
blue = "0x7cafc2"
cyan = "0x86c1b9"
green = "0xa1b56c"
magenta = "0xba8baf"
red = "0xab4642"
white = "0xd8d8d8"
yellow = "0xf7ca88"

[colors.primary]
background = "0x2d2d2d"
foreground = "0xd8d8d8"

[font]
size = 19

[font.normal]
family = "Iosevka Nerd Mono"

[shell]
args = ["--login"]
program = "/usr/bin/fish"

[window]
decorations = "none"
decorations_theme_variant = "Dark"

[window.padding]
x = 20
y = 20

[[hints.enabled]]
command         = "xdg-open"
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
binding         = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|news:|file:|ssh:|[a-z]+://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
