#!/bin/bash

# Paths

APPLET_PATH="${HOME}/.config/i3/statusbar/applets"
TEMP_PATH="/tmp/i3statusbar.$$"
EVENT_PATH="${TEMP_PATH}/__events"

# Colors

COLOR_ICON="#ab4642"
COLOR_TEXT="#d8d8d8"

# Icons

ICON_BATTERY_0="e800"
ICON_BATTERY_25="e801"
ICON_BATTERY_50="e802"
ICON_BATTERY_75="e803"
ICON_BATTERY_100="e804"
ICON_BATTERY_CHARGE="e805"

ICON_CLOCK="e806"
ICON_CPU="e807"
ICON_MEMORY="e808"
ICON_TEMP="e809"

ICON_WIRELESS_0="e80a"
ICON_WIRELESS_25="e80b"
ICON_WIRELESS_50="e80c"
ICON_WIRELESS_100="e80d"
ICON_WIRED="e80e"

ICON_VOLUME_0="e80f"
ICON_VOLUME_25="e810"
ICON_VOLUME_50="e811"
ICON_VOLUME_100="e812"

ICON_MUSIC_IDLE="e816"
ICON_MUSIC_PAUSE="e813"
ICON_MUSIC_STOP="e815"
ICON_MUSIC_PLAY="e814"

# Applet-specific configuration

# Battery name, e.g. `BAT0`, `BAT1`
BATTERY_NAME="BAT1"

# Clock date format, run `man date` for more information
CLOCK_FORMAT="%a %d, %H:%M"

# Update interval for CPU applet, in seconds
CPU_UPDATE_INTERVAL="5"

# Update interval for memory applet, in seconds.
MEMORY_UPDATE_INTERVAL="5"

# Backend to use for network information, choices: `connman`, `networkmanager`
NETWORK_BACKEND="connman"
NETWORK_CLICK_CMD="connman-gtk --no-icon"

# Backend to use for player information, choices: `mpd`, `mpris`
PLAYER_BACKEND="mpd"
PLAYER_CLICK_CMD="eval termite -t 'Music Player' -e ncmpcpp"

# Script to use for controlling volume
VOLUME_SCRIPT="~/.config/i3/bin/volume"
VOLUME_CLICK_CMD="pavucontrol"
