#!/bin/bash

bar() {
	# Bar length.
	length="${2:-10}"

	# Print full segments.
	full=$((${1} / ${length}))
	for i in $(seq 1 ${full})
	do
		printf '\u2588'
	done

	# Print remaining empty segments.
	empty=$(((100 - ${1}) / ${length}))
	for i in $(seq 0 ${empty})
	do
		printf '\u2591'
	done
}

icon() {
	printf "\u${1}"
}

quit() {
	echo "Quitting..."

	# Kill all child processes.
	pkill -TERM -P $$

	# Clean up shared resources.
	rm -R "${TEMP_PATH}"

	# Exit with defined code.
	exit ${1:-0}
}